### ISSUE TITLE
1.a.1.a.1.a.2 Have you been in contact with a data protection official or other inspectorates? 

### ISSUE THREAD

**Issue by DSW-ELIXIR-NO-feedback** [elixir-no-nels/DSW-ELIXIR-NO-feedback#108]
The description does not match the question.

**Comment by tinavisnovska** [comment]
Adding comments about why the question confuses me:

If the question asks about contact with inspectorates in the organizations that contributors are affiliated to, then writing this more clearly would be good idea.

Alternatively, if the question refers to some entities that provide some sort of consulting about the topic nationally or otherwise, then elaborating on this would be more than useful, ideally with naming some examples or something,...

**Comment by tinavisnovska** [comment]
Also, in 1.a.1.a.1.a.6 What is the legal basis for processing the personal data, "Data Protection Officer" is used probably in the same context as "data protection official" here, make this consistent.
