### ISSUE TITLE
Questions 2 and 3 in VII. Preserving data

### ISSUE THREAD

**Issue by tinavisnovska** [elixir-no-nels/DSW-ELIXIR-NO-feedback#132]
When using compute capacity provided by someone else, like NeLS or TSD, this is more of a question for the service provider than for the user, it would make sense to have those options covered and guide the user through the questions, explaining what their answers should be.

**Comment by korbinib** [comment]
Yes, but this is the idea for the pre-populated templates.

**Comment by bianchini88** [comment]
In these regards, would it make sense to have some minimal pre-populated templates covering NeLS or TSD? So that users not associated with one of the research infrastructures can also get a little help.

**Comment by korbinib** [comment]
[These](https://elixir-no.ds-wizard.org/projects/3e291e41-18c4-4fd5-b588-1d19303ed6bb) are the base recommendations the specific recommendations are based on. However I think already choosing a storage infrastructure without knowing anything about the project can be tricky. Also there is also HUNT Cloud, EUTROS and SAFE. - We could comment these questions however instead of per-filling them?

**Comment by bianchini88** [comment]
Are the base recommendations also to become a template? I quite like the idea of having a "neutral" one. 
"We could comment these questions however instead of per-filling them?" This is also fine!
